---
AWSTemplateFormatVersion: '2010-09-09'
Description: >

  This Cloudformation Template deploys the Coturn / Turn Server for the video and audio handling.

  Disclaimer: Not for production use. Demo and testing purposes only.

  Author: David Surey <suredavi@amazon.com>

Parameters:
  BBBOperatorEMail:
    Description: E-Mail address to notify if there are any operational issues
    Type: String
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: Must be a valid email address.
    Default: johndoe@example.com
  BBBNotificationTopic:
    Description: Topic to be used for alarm notifications
    Type: String
  BBBPublicApplicationSubnets:
    Description: Comma separated list of the appserver's subnets
    Type: CommaDelimitedList
  BBBTurnInstanceAMI: 
    Description: Ubuntu AMIID to be deployed for Turn Instances 
    Type: String
  BBBApplicationVersion:
    Description: Version of the Big Blue Button Application
    Type: String
    Default: focal-250
  BBBTurnInstanceType:
    Description: Instance type for the turn server
    Type: String
    Default: t3a.medium
  BBBTurnMaxInstances:
    Type: Number
    Description: Maximum number of turn server instance
    Default: 1
  BBBTurnMinInstances:
    Type: Number
    Description: Minimum number of turn server instance
    Default: 1
  BBBTurnDesiredInstances:
    Type: Number
    Description: Desired number of turn server instance
    Default: 1
  BBBTurnSecurityGroup:
    Description: Security Group that should be assigned for the turn server
    Type: String
  BBBHostedZone:
    Description: Hosted zone in which the DNS entries for the app servers should be created
    Type: String
  BBBDomainName:
    Description: Base domain name used for the instance
    Type: String
  BBBStackBucketStack:
    Description: S3 Bucket Stack that contains scripts and sources
    Type: String
  BBBSystemLogsGroup:
    Description: Log group to be used for the system logs
    Type: String
  BBBApplicationLogsGroup:
    Description: Log group to be used for the Application logs
    Type: String
  BBBSystemLogsGroupArn:
    Description: Log group to be used for the system logs
    Type: String
  BBBApplicationLogsGroupArn:
    Description: Log group to be used for the Application logs
    Type: String

Resources:
  BBBTurnSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the BBB Database instance secret'
      GenerateSecretString:
        SecretStringTemplate: '{"turnkeyname": "turnsecretkey"}'
        GenerateStringKey: 'turnkeyvalue'
        PasswordLength: 16
        ExcludePunctuation: 'true'

  BBBTurnHostnameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: turnhostname
      Type: String
      Value: placeholder
      Description: SSM Parameter for the variable part of the turn hostname

  BBBTurnAutoScaling:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref BBBPublicApplicationSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref BBBTurnInstanceLaunchTemplate
        Version: !GetAtt BBBTurnInstanceLaunchTemplate.LatestVersionNumber
      TerminationPolicies:
        - DEFAULT
      MaxSize: !Ref BBBTurnMaxInstances
      MinSize: !Ref BBBTurnMinInstances
      DesiredCapacity: !Ref BBBTurnDesiredInstances
      NotificationConfiguration:
        TopicARN:
          Ref: BBBNotificationTopic
        NotificationTypes:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true

  BBBTurnEC2Role:
    Type: AWS::IAM::Role
    DependsOn:
      - BBBTurnHostnameParameter
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]
      Path: /
      Policies:
        - PolicyName: TurnEC2Role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                  - route53:GetHostedZone
                  - route53:ListResourceRecordSets
                Resource: !Sub "arn:aws:route53:::hostedzone/${BBBHostedZone}"
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref BBBTurnSecret
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${BBBStackBucketStack}/*"
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/turnhostname"
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:CreateLogGroup
                Resource:
                  - !Ref BBBSystemLogsGroupArn
                  - !Ref BBBApplicationLogsGroupArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  BBBTurnEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref BBBTurnEC2Role

  BBBTurnInstanceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt BBBTurnEC2InstanceProfile.Arn
        ImageId: !Ref BBBTurnInstanceAMI
        InstanceType: !Ref BBBTurnInstanceType
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: 0
            Groups:
              - !Ref BBBTurnSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe

            apt update -y
            
            while fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
            
            DEBIAN_FRONTEND='noninteractive' apt -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' full-upgrade
            
            apt autoremove -y
            apt autoclean
            
            while fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
            
            apt install -y git binutils python3-pip build-essential python-dev python-setuptools jq letsencrypt
            pip3 install -U awscli
            
            while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done

            aws s3 cp s3://${BBBStackBucketStack}/bbb-turnserver-bootstrap.sh /tmp/bbb-turnserver-bootstrap.sh
            chmod +x /tmp/bbb-turnserver-bootstrap.sh 
            
            /tmp/bbb-turnserver-bootstrap.sh -a ${BBBStackBucketStack} \
            -b ${BBBSystemLogsGroup} \
            -c ${BBBDomainName} \
            -d ${BBBTurnHostnameParameter} \
            -e ${BBBHostedZone} \
            -f ${BBBTurnSecret} \
            -g ${BBBOperatorEMail} \
            -h ${BBBApplicationVersion} \
            -i ${AWS::Region}

            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource BBBTurnAutoScaling --region ${AWS::Region} || true

Outputs:
  BBBTurnSecret:
    Description: The Big Blue Button Turn Secret Key
    Value:
      Ref: BBBTurnSecret
  BBBTurnHostnameParameter:
    Description: The Parameter containing the Big Blue Button Turn Hostname
    Value:
      Ref: BBBTurnHostnameParameter
  BBBTurnEC2InstanceProfile:
    Description: Big Blue Button Turn Instance Profile
    Value:
      Ref: BBBTurnEC2InstanceProfile
  BBBTurnEC2Role:
    Description: Big Blue Button Turn Instance Role
    Value:
      Ref: BBBTurnEC2Role
  BBBTurnAutoScaling:
    Description: Big Blue Button Turn Instance Autoscaling Group
    Value:
      Ref: BBBTurnAutoScaling
  BBBTurnInstanceLaunchTemplate:
    Description: Big Blue Button Turn Instance Launch Template
    Value:
      Ref: BBBTurnInstanceLaunchTemplate
